### ISSUE TITLE
running question

### ISSUE THREAD

**Issue by Michael-Fuu** [ac-93/soft-actor-critic#1]
Hi,
    As you didn't explain how to run your code, I tried to copy your code(./soft-actor-critic/array_observation/sac_discrete/) to spiningup folder(./spinningup/spinup/algos/tf1/) .But it didn't work, **can you explain how to run your code,**please?

**Comment by Michael-Fuu** [comment]
hi，
    I still can run this code sucessfully, help

**Comment by ac-93** [comment]
Hi, 

If you clone the repo and run the command 

```python array_observation/sac_cont/sac.py```

from the base directory you should start training a continuous sac agent on the pendulum environment.

The training parameters including which environment are set at the bottom of the sac.py files in there corresponding directories, this is slightly different to spinningup where hyper params are passed as arguments.

Make sure spinningup is installed in your environment as these algorithms rely on some of the utils provided by spinningup. 

If you're still having problems let me know what errors being thrown and I'll try to help!

**Comment by Michael-Fuu** [comment]
Hi,
Thanks for your kindly respoonse, 
However I still have some problems. I run the command  `python array_observation/sac_discrete/sac.py` after changing environment into 'Boxing-ram-v0' and then plot the process.
![image](https://user-images.githubusercontent.com/55577878/88665227-e501be00-d110-11ea-9e1a-a344d47f57be.png)
that seems something went wrong? 
another problem is that when I run an agent in atari environment with image_observation/sac_discrete/sac.py, program would stuck during the running process:
![image](https://user-images.githubusercontent.com/55577878/88666776-1b403d00-d113-11ea-9846-2ea1716ace02.png)

**Comment by ac-93** [comment]
Hmm, I haven't used the atari_ram environments much so I'm not sure if this is a bug or just a bad training run.

For some of the atari envs certain tricks are used to improve performance such as storing a termination=True when a life is lost and automatic firing when environments are reset. These are done in ```image_observation/sac_discrete_atari/sac.py``` but not for array observations. However, I don't know if they will have much of an effect for the boxing game. 

The default hyper-params setup in the script you run are probably not well suited to atari games. The image observation scripts will be more suited to training atari agents however they require quite a bit more compute. If you have the resources I would recommend giving those a go as you'll likely see better results.

The output you're seeing seems to be warnings related to tensorflow, I don't think they're responsible as I see similar training curves on my machine without those warnings.

Edit** Sorry I didn't read your comment properly, which version of tensorflow are you using? I don't see those errors on tensorflow 1.15.3.
