### ISSUE TITLE
Alpha Loss in SAC

### ISSUE THREAD

**Issue by xingdi-eric-yuan** [ac-93/soft-actor-critic#2]
Hi @ac-93 , I'm wondering why `log_alpha` is used [HERE](https://github.com/ac-93/soft-actor-critic/blob/master/image_observation/sac_discrete_atari/sac.py#L132) rather than `alpha`. Am I understanding wrong somewhere? Thanks!

**Comment by ac-93** [comment]
Hi there, you're not understanding wrong, the correct equation does have `alpha` at that point. Using `log_alpha` is just a trick used to improve numerical stability as the range is better suited to optimisation. I believe the same value of `alpha` will be optimal in both functions so  it's possible to swap out like this.

**Comment by xingdi-eric-yuan** [comment]
I see, thanks, @ac-93 .
